# Site Settings
encoding: UTF-8
exclude: ["*.gem", "*.gemspec", "Gemfile", "Gemfile.lock", "node_modules", "Rakefile", "starter-kit", "vendor"]
lang: zh-cn # Language code as defined in _data/i18n.yml. en, en-gb, en-us, zh, zh-cn, zh-tw etc.
permalink: /blog/:year/:month/:day/:title/

whitelist: [jekyll-feed, jekyll-redirect-from, jekyll-seo-tag, jekyll-sitemap]
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
kramdown:
  auto_id_prefix: 'heading-'
  smart_quotes: ["apos", "apos", "quot", "quot"]
  toc_levels: 1..3

sass:
  style: compressed

# Site Data
url: https://techy-wu.github.io/Let-s_Pick_UWP/ # the base hostname & protocol for your site, e.g. http://example.com
baseurl: / # the subpath of your site, e.g. /blog
title: Let's Pick UWP
description: "轻便美观高效的随机抽取解决方案"
keywords: 'pick,solution,uwp-based,software'
author:
  name: Techy Wu
  job_title:
  location:
  email: Techy_Wu@outlook.com
  social_links:
    - name: 
      url:
    - name: github
      url: https://github.com/Techy-Wu
    - name: instagram
      url:
    - name: linkedin
      url:
    - name: stackoverflow
      url:
    - name: twitter
      url: 
    - name: vk
      url:
home:
  section1: <h1>Let's Pick UWP</h1>
  section2: <h2>轻便 美观 高效 的随机抽取解决方案</h2>
  section3: <div class="social-links"><a class="ico-github btn" href="https://github.com/Techy-Wu/Let-s_Pick_UWP" title="View on GitHub"></a></div>
blog:
  cc_license: http://creativecommons.org/licenses/by-nd/4.0/ # A link to CC License of your choice.
  cc_license_image: /assets/images/theme/cc-by-nd.png # An image of your CC License. 
  footer_content: 轻便 美观 高效 的随机抽取<a href="https://github.com/Techy-Wu/Let-s_Pick_UWP">解决</a>方案.

disqus:
  shortname: # e.g. yizeng
  public_key: # e.g. ULZ0b9TFefCUJHKQd4JCKv2v3u27YoG7YG8zXPewkWrT333Z0Se9YnxLzoV6VM8W
google_tag_manager: # e.g. 'GTM-KCQJXZ8F'
addthis_public_id: # AddThis sharing plugin. See http://www.addthis.com/. E.g. ra-53329e27694534j5 

paths:
  home: /
  blog: /blog/
  categories: /blog/categories/
  tags: /blog/tags/
